### ISSUE TITLE
无法显示数据库列表，故导致执行sql时提示要先选中数据库

### ISSUE THREAD

**Issue by KillerMan12345** [guohai163/java-sql-web#1]
![image](https://user-images.githubusercontent.com/16752597/147620573-104832d0-2765-407e-834c-fdd2b97ab02b.png)
无法显示数据库列表，故导致执行sql时提示要先选中数据库
![image](https://user-images.githubusercontent.com/16752597/147620637-15288401-cabd-40d9-a4cb-4fe22dcda9a1.png)

**Comment by guohai163** [comment]
先确认下所填写的数据库 类型、用户名密码、端口是否正确？
跑jsw的机器是否够到达所选数据库服务器。

稍后我在数据库配置界面增加一个连接测试选项。

**Comment by KillerMan12345** [comment]
jsw是用你的docker 镜像 在docker里跑的，账号密码应该都正确，我试下ip是否通看看。
新增链接测试选项，是会发布新的镜像版本吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guohai163/java-sql-web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月29日(星期三) 上午10:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [guohai163/java-sql-web] 无法显示数据库列表，故导致执行sql时提示要先选中数据库 (Issue #1)





 
先确认下所填写的数据库 类型、用户名密码、端口是否正确？
 跑jsw的机器是否够到达所选数据库服务器。
 
稍后我在数据库配置界面增加一个连接测试选项。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guohai163** [comment]
用docker exec -it container_name bash命令进到容器里试下telnet dbserver dbprot.看看边通性。

会的，我增加完功能后发布个新版本镜像，目前源码的程序版本已经到了0.7.0了

**Comment by KillerMan12345** [comment]
好的，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guohai163/java-sql-web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月29日(星期三) 中午11:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [guohai163/java-sql-web] 无法显示数据库列表，故导致执行sql时提示要先选中数据库 (Issue #1)





 
用docker exec -it container_name bash命令进到容器里试下telnet dbserver dbprot.看看边通性。
 
会的，我增加完功能后发布个新版本镜像，目前源码的程序版本已经到了0.7.0了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guohai163** [comment]
目前源码和docker镜像版本都已升级到0.7.5 增加了数据库连接性测试功能

在增加新DB时可以单击连接..进行相应的测试

![1](https://raw.githubusercontent.com/guohai163/demo/master/conntest-1.png)
![2](https://raw.githubusercontent.com/guohai163/demo/master/conntest-2.png)
![3](https://raw.githubusercontent.com/guohai163/demo/master/conntest-3.png)

**Comment by KillerMan12345** [comment]
谢谢告知！😁



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月29日(周三) 晚上11:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [guohai163/java-sql-web] 无法显示数据库列表，故导致执行sql时提示要先选中数据库 (Issue #1)




 
目前源码和docker镜像版本都已升级到0.7.5 增加了数据库连接性测试功能
 
在增加新DB时可以单击连接..进行相应的测试
 

 
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guohai163** [comment]
问题解决了吗，可以看到数据库列表了吗

**Comment by KillerMan12345** [comment]
解决了的（是容器没有对外暴露端口导致的），但是没看到你新增的那个测试连接的功能。


另外是否后续可以考虑允许做更新插入的操作，针对用户或库做读写权限控制？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guohai163/java-sql-web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月30日(星期四) 下午2:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [guohai163/java-sql-web] 无法显示数据库列表，故导致执行sql时提示要先选中数据库 (Issue #1)





 
问题解决了吗，可以看到数据库列表了吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guohai163** [comment]
解决就好。

目前不考虑增加写入之类的操作，那个可能用客户端版本的终端工具更合适。
这个项目的原始需求是我的团队需要一个只查的功能，而且需要对查询人、查询语句进行记录。以及限制查询结果的条数上限。
